# Generated by Django 4.1.7 on 2023-03-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('livro', '0006_livros_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='Usuario',
        ),
        migrations.AddField(
            model_name='livros',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
