# Generated by Django 4.1.7 on 2023-03-18 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_remove_turma_color_livros_nome_turma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='nome_turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome_turma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
