# Generated by Django 4.1.7 on 2023-03-18 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_turma_usuario_nome_turma'),
        ('livro', '0014_alter_livros_nome_turma_alter_turma_nome_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='nome_turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.turma'),
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
