# Generated by Django 4.1.7 on 2023-03-25 02:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_telefone_alter_usuario_turma'),
        ('livro', '0017_alter_livros_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livros',
            options={},
        ),
        migrations.RemoveField(
            model_name='livros',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='data_emprestimo',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='nome_emprestado',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='nome_turma',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='tempo_duracao',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestado', models.BooleanField(default=False)),
                ('nome_emprestado', models.CharField(blank=True, max_length=120, null=True)),
                ('data_emprestimo', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('tempo_duracao', models.DurationField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='livro.categoria')),
                ('nome_turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.turma')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Livro',
            },
        ),
    ]
