# Generated by Django 4.1.7 on 2023-03-25 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0018_alter_livros_options_remove_livros_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='emprestado',
        ),
    ]
