# Generated by Django 4.1.7 on 2023-03-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0021_rename_titulo_emprestimos_emprestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='emprestimo',
            field=models.BooleanField(default=False),
        ),
    ]
