# Generated by Django 4.1.7 on 2023-03-29 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0022_emprestimos_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='categoria',
        ),
        migrations.AddField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.categoria'),
            preserve_default=False,
        ),
    ]
