# Generated by Django 4.1.7 on 2023-03-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0023_remove_emprestimos_categoria_livros_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='emprestimo',
        ),
        migrations.AddField(
            model_name='livros',
            name='emprestimo',
            field=models.BooleanField(default=False),
        ),
    ]
