# Generated by Django 4.1.7 on 2023-03-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0025_emprestimos_emprestimos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='emprestimos',
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='emprestimo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='emprestimo',
            field=models.BooleanField(default=True),
        ),
    ]
