# Generated by Django 4.1.7 on 2023-03-29 22:07

from django.db import migrations, models
import livro.models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0026_remove_emprestimos_emprestimos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='emprestimo',
            field=models.BooleanField(default=True, verbose_name=livro.models.Livros),
        ),
    ]
