# Generated by Django 4.1.7 on 2023-03-29 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0028_remove_emprestimos_emprestimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestimo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='emprestimo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.emprestado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livros',
            name='emprestimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='livro.emprestado'),
        ),
    ]
