# Generated by Django 4.1.7 on 2023-03-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0030_alter_emprestimos_emprestimo_alter_livros_emprestimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestado',
            old_name='emprestimo',
            new_name='emprestar',
        ),
    ]
