# Generated by Django 4.1.7 on 2023-03-29 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0031_rename_emprestimo_emprestado_emprestar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='emprestimo',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='emprestimo',
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='emprestar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.emprestado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='emprestar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.emprestado'),
            preserve_default=False,
        ),
    ]
