# Generated by Django 4.1.7 on 2023-03-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0032_remove_emprestimos_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='emprestar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.emprestado'),
        ),
    ]
