# Generated by Django 4.1.7 on 2023-03-29 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0034_alter_emprestimos_emprestar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='emprestar',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='emprestar',
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.categoria'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Emprestado',
        ),
    ]
