# Generated by Django 4.1.7 on 2023-03-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0035_remove_emprestimos_emprestar_remove_livros_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='emprestar',
            field=models.BooleanField(default=False),
        ),
    ]
