# Generated by Django 4.1.7 on 2023-03-29 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0036_emprestimos_emprestar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='emprestar',
        ),
    ]
