# Generated by Django 4.1.7 on 2023-03-29 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0038_emprestimos_estaemprestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='estaEmprestado',
        ),
    ]
