# Generated by Django 4.1.7 on 2023-03-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0039_remove_emprestimos_estaemprestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
    ]
