# Generated by Django 4.1.7 on 2023-03-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0040_livros_emprestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='estaEMprestado',
            field=models.BooleanField(default=False),
        ),
    ]
