# Generated by Django 4.1.7 on 2023-03-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0041_emprestimos_estaemprestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='emprestado',
        ),
    ]
