# Generated by Django 4.1.7 on 2023-03-30 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0042_remove_livros_emprestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimos',
            old_name='estaEMprestado',
            new_name='esta_emprestado',
        ),
    ]
