# Generated by Django 4.1.7 on 2023-03-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0043_rename_estaemprestado_emprestimos_esta_emprestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='esta_emprestado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
