# Generated by Django 4.1.7 on 2023-03-20 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_nome_turma_usuario_turma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='nome_turma',
            new_name='nome',
        ),
    ]
