# Generated by Django 4.1.7 on 2023-03-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_nome_turma_nometurma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='nometurma',
            new_name='nome',
        ),
    ]
